##########      Defaults    #############
x-defaults: &defaults
  image: "${OL_IMAGE}"
  restart: "on-failure"
  network_mode: host  # Fixme (nourspace): required to detect node processes?
  pid: host           # Fixme (nourspace): required to detect node processes?
  volumes:
    - "node_data:/root/.0L"
    - "epoch_archive:/root/epoch-archive"
  ulimits:
    nproc: 500000
    nofile: 500000
  entrypoint: [ "" ]
  env_file:
    - "./.env"

x-util-defaults: &util-defaults
  <<: *defaults
  restart: "no"
  command: [ "tail", "-f", "/dev/null" ]

###########################################

version: "3.8"
services:
  ##########  Main services   #############

  node:
    <<: *defaults
    container_name: "0l-${OL_NODE_MODE}"
    command:
      [
        "diem-node",
        "--config",
        "/root/.0L/${OL_NODE_MODE}.node.yaml"
      ]
    ports:
      - "6179:6179"
      - "6180:6180"
      - "8080:8080"

  tower:
    <<: *defaults
    container_name: 0l-tower
    command: "tower ${OL_TOWER_OPERATOR} ${OL_TOWER_USE_FIRST_UPSTREAM} ${OL_TOWER_VERBOSE} start"
    environment:
      NODE_ENV: "prod"
      TEST: "${OL_TOWER_TEST-n}"

  monitor:
    <<: *defaults
    container_name: 0l-monitor
    command: [ "ol", "serve" ]
    ports:
      - "3030:3030"

  remote:
    image: "${OL_TOOLS_IMAGE}"
    container_name: 0l-remote-operator
    restart: "on-failure"
    ports:
      - "3333:3333"
    volumes:
      - "./remote_operator:/code"

  ########## Utility services #############

  shell:
    <<: *util-defaults
    container_name: 0l-shell

  source:
    <<: *util-defaults
    image: "${OL_IMAGE}-source"
    container_name: 0l-source

  builder:
    <<: *util-defaults
    image: "${OL_IMAGE}-builder"
    container_name: 0l-builder

volumes:
  node_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${OL_DATA_DIR}"
  epoch_archive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${OL_EPOCH_ARCHIVE_DIR}"
