version: "3.8"
services:

  shell:
    image: "${OL_IMAGE}"
    container_name: 0l-shell
    restart: "no"
    network_mode: host
    pid: host
    volumes:
      - "node_data:/root/.0L"
    entrypoint: [ "bash" ]
    ulimits:
      nproc: 100000
      nofile: 100000
    env_file:
      - "./.env"

  node:
    image: "${OL_IMAGE}"
    container_name: "0l-${OL_NODE_MODE}"
    restart: "always"
    network_mode: host
    pid: host
    volumes:
      - "node_data:/root/.0L"
    entrypoint:
      [
        "diem-node",
        "--config",
        "/root/.0L/${OL_NODE_MODE}.node.yaml"
      ]
    ports:
      - "6179:6179"
      - "6180:6180"
      - "8080:8080"
    ulimits:
      nproc: 100000
      nofile: 100000
    env_file:
      - "./.env"

  tower:
    image: "${OL_IMAGE}"
    container_name: 0l-tower
    restart: "always"
    network_mode: host
    pid: host
    volumes:
      - "node_data:/root/.0L"
    entrypoint: [ "tower", "${OL_TOWER_OPERATOR}", "${OL_TOWER_VERBOSE}", "start" ]
    ulimits:
      nproc: 100000
      nofile: 100000
    environment:
      NODE_ENV: "prod"
    env_file:
      - "./.env"

  monitor:
    image: "${OL_IMAGE}"
    container_name: 0l-monitor
    restart: "always"
    network_mode: host # Fixme (nourspace): required to detect node processes?
    pid: host # Fixme (nourspace) required to detect node processes?
    volumes:
      - "node_data:/root/.0L"
    entrypoint: [ "ol", "serve" ]
    ports:
      - "3030:3030"
    ulimits:
      nproc: 100000
      nofile: 100000
    env_file:
      - "./.env"

volumes:
  node_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${OL_DATA_DIR}"
