version: '3'

vars:
  # Extracts values from .env file
  IMAGE:
    sh: grep -v '^#' .env | grep -e "OL_IMAGE" | sed -e 's/.*=//'
  REPO:
    sh: grep -v '^#' .env | grep -e "OL_REPO" | sed -e 's/.*=//'
  BRANCH:
    sh: grep -v '^#' .env | grep -e "OL_BRANCH" | sed -e 's/.*=//'
  TOOLS_IMAGE:
    sh: grep -v '^#' .env | grep -e "OL_TOOLS_IMAGE" | sed -e 's/.*=//'

tasks:
  docker:build:
    desc: "Build docker images"
    cmds:
      - docker build --build-arg BRANCH={{.BRANCH}} --build-arg REPO={{.REPO}} --tag {{.IMAGE}} .
      - task docker:build:source
      - task docker:build:builder

  docker:build:source:
    desc: "Build docker [source] image"
    cmds:
      - docker build --build-arg BRANCH={{.BRANCH}} --build-arg REPO={{.REPO}} --tag {{.IMAGE}}-source --target source .

  docker:build:builder:
    desc: "Build docker [builder] image"
    cmds:
      - docker build --build-arg BRANCH={{.BRANCH}} --build-arg REPO={{.REPO}} --tag {{.IMAGE}}-builder --target builder .

  docker:build:tools:
    desc: "Build docker [tools] image"
    cmds:
      - docker build -f tools.Dockerfile --tag {{.TOOLS_IMAGE}} .

  docker:push:
    desc: "Push docker image"
    cmds:
      - docker push {{.IMAGE}}

  docker:push:source:
    desc: "Push docker [source] image"
    cmds:
      - docker push {{.IMAGE}}-source

  docker:push:builder:
    desc: "Push docker [builder] image"
    cmds:
      - docker push {{.IMAGE}}-builder

  docker:push:tools:
    desc: "Push docker [tools] image"
    cmds:
      - docker push {{.TOOLS_IMAGE}}

  shell:
    desc: "Start a shell container"
    cmds:
      - docker compose up -d shell
      - docker compose exec shell bash

  source:
    desc: "Start a source container"
    cmds:
      - docker compose up -d source
      - docker compose exec source bash

  builder:
    desc: "Start a builder container"
    cmds:
      - docker compose up -d builder
      - docker compose exec builder bash

  clean-utils:
    desc: "Clean utility containers"
    cmds:
      - docker compose stop shell source builder
      - docker compose rm shell source builder
