version: '3'

vars:
  IMAGE: "nourspace/0l"
  TAG: "v5.0.6"
  
tasks:

  docker:build:
    desc: Build docker image
    cmds:
      - docker build --build-arg TAG={{.TAG}} --tag {{.IMAGE}}:{{.TAG}} .

  docker:push:
    desc: Push docker image
    cmds:
      - docker push {{.IMAGE}}:{{.TAG}}

  docker:shell:
    desc: "Start a shell in node"
    cmds:
      - docker run --rm -it {{.IMAGE}}:{{.TAG}} /bin/bash

  onboard:val:
    cmds:
      - '# Onboarding validator!'
      - docker run --rm -it {{.IMAGE}}:{{.TAG}} onboard:val -- {{.CLI_ARGS}}

  node:account.json:
    cmds:
      - 'Retriving account.json'
      - docker cp .....
